#! /usr/bin/env zsh

emulate -L zsh
set -eu -o pipefail

me=${0:t}

help="
usage:
  $me

environment:
  TTW_GHCS
    if set and non-null, overrides default set of GHC versions to test
    example:
      TTW_GHCS='9.12.2 9.10.2' $me
"

case ${1-} in (-h|--help) <<< $help && exit 0;; esac

ghcs_default=(
  9.12.2
  9.10.2
  9.8.4
  9.6.7
  9.4.8
  )

ghcs=( ${=${TTW_GHCS:-$ghcs_default}} )

integer -i runTests

foreach v ( $ghcs ) {
  print
  print "***"
  print "*** version: $v"
  print "***"

  runTests=1

  opts=(
    -v0
    --with-compiler=ghc-$v
    --project-file=cabal.project.no-local
    --prefer-oldest
    )

  rm -rf dist-newstyle/cache/ \
         dist-newstyle/build/

  true         && cabal $opts           build && print "OK (build)"
  ((runTests)) && cabal $opts -fdoctest test  && print "OK (test)"
}

print
print '*** DONE.'
print
